### ISSUE TITLE
Milestone 1 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/sylvia_patrick_Titanic_Survival_ML#41]
**You may close this issue when all issues are resolved and checked.** 

**Mechanics**
- [ ] In your main README.md, provide a short description of what each script does including its outputs. Your explanation could include a flow chart/dependecy diagram. 
- [ ] Describe the type of variables (e.g., categorical, ordinal, numeric, etc). 

**Reasoning**

**Visualization**
- [ ] You displayed no figures, only tables in the report...
- [ ] Its a good practice to plot a line graph of the cross-validation scores and tree depth so that the reader can visualize why you selected the respective tree depth and to assess over-fitting. 
- [ ] It is also a good idea to visualize the decision tree to understand how the model works. 

**Quality -- Readability and Documentation**
- [ ] Make your model reproducible. See [this](http://scikit-learn.org/stable/faq.html#how-do-i-set-a-random-state-for-an-entire-execution). 

**Quality -- Robustness and Maintainability**
- [ ] Should have a unit test for each function (other than the main function)

**Grammar and Spelling**
_Report:_
Misspelled: moment, designated, frequencies, during, quantitatively, adequately,

**Comment by aimirza** [comment]
Still several past issues not addressed. 
- [ ] You created results/figure/decision_tree.png but it is not incorporated into the report. You talked about the decision tree though the figure is not present in the report. 
- [ ] Makefile is hard to read because of all the long paths

**Comment by tungpatrick** [comment]
We have updated all the issues you have provided feedback on. Thank you very much.
